### ISSUE TITLE
About when to call destroy()

### ISSUE THREAD

**Issue by nekohasekai** [SagerNet/cronet-go#2]
Sorry not familiar with c/c++.

When do I need to call destroy() for a cronet-created structure (like RequestFinishedInfo), or not? And what about incoming parameters like HttpHeader?

@klzgrad

**Comment by klzgrad** [comment]
```
   * @param request_info {@link RequestFinishedInfo} for finished request.
   *     Ownership is *not* transferred by this call, do not destroy
   *     {@code request_info}.
```
