### ISSUE TITLE
how can i use proxy through  http.client with cronet transport ?

### ISSUE THREAD

**Issue by 2qif49lt** [SagerNet/cronet-go#9]
dont find DialContext or Proxy field.

thank for your work.

**Comment by 2qif49lt** [comment]
solved

**Comment by sleeyax** [comment]
@2qif49lt how did you solve it?? 

It seems like the following code doesn't work if the proxy requires authentication:
```go
engineParams.SetExperimentalOptions(fmt.Sprintf(`{"proxy_server": "%s"}`, "http://username:password@ip:port"))
```
